# DataSource Config
spring:
  datasource:
    # comment below param in online environment!
    initialization-mode: always
    # auto detected from url
    # driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:mysql/schema.sql
    data: classpath:mysql/data.sql
    url: jdbc:mysql://localhost/test
    # url: jdbc:h2:mem:test
    username: root
    password: secret

# Logger Config
logging:
  level:
    root: WARN
    org.springframework: OFF
    com.li3huo.mybatisplus.demo: debug

# User Define Value
test:
  key: abc 
