spring:
  # DataSource Config
  datasource:
    # comment below param in online environment!
    initialization-mode: always
    # auto detected from url
    # driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:mysql/schema.sql
    data: classpath:mysql/data.sql
    url: jdbc:mysql://localhost/mp-test?characterEncoding=utf8
    # url: jdbc:h2:mem:test
    username: root
    password: secret
  # Cache Config
  cache:
    type: redis
    cache-names:
    - ExamItems
    redis:
      time-to-live: 60000
      cache-null-values: false
  # Redis Config
  redis:
    host: localhost

# MP config
mybatis-plus:
  type-enums-package: com.li3huo.mybatisplus.demo.entity.enums

# Logger Config
logging:
  level:
    root: WARN
    org.springframework: OFF
    com.li3huo.mybatisplus.demo: debug

# User Define Value
test:
  key: abc 
