spring:
  main:
    banner-mode: "off"

server:
  port: 8080

endpoints:
  actuator: 
    enabled: false
    sensitive: false


logging:
  level:
    root: WARN
    org.springframework: OFF
    com.example.demo: DEBUG
